### ISSUE TITLE
 Error on imageRaster function

### ISSUE THREAD

**Issue by sbrsubuvga** [andrey-ushakov/esc_pos_printer#94]
on print image raster getting an error 

```
E/flutter (29670): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..152976: 152977
E/flutter (29670): #0      List.[] (dart:core-patch/growable_array.dart:177:60)
E/flutter (29670): #1      Ticket._packBitsIntoBytes (package:esc_pos_utils/src/ticket.dart:566:16)
E/flutter (29670): #2      Ticket._toRasterFormat (package:esc_pos_utils/src/ticket.dart:675:12)
E/flutter (29670): #3      Ticket.imageRaster (package:esc_pos_utils/src/ticket.dart:694:38)
E/flutter (29670): #4      _PrinterEntryState.testTicket (package:project/printerEntry.dart:556:15)
E/flutter (29670): <asynchronous suspension>
E/flutter (29670): #5      _PrinterEntryState.testPrint (package:project/printerEntry.dart:503:24)
E/flutter (29670): <asynchronous suspension>
E/flutter (29670): 
```

**Comment by mjafartp** [comment]
Latest Ver. also have the same error on printing generated image 

E/flutter ( 7499): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..1584016: 1584017
E/flutter ( 7499): #0      List.[] (dart:core-patch/growable_array.dart:183:60)
E/flutter ( 7499): #1      Generator._packBitsIntoBytes (package:esc_pos_utils/src/generator.dart:207:16)
E/flutter ( 7499): #2      Generator._toRasterFormat (package:esc_pos_utils/src/generator.dart:193:12)
E/flutter ( 7499): #3      Generator.imageRaster (package:esc_pos_utils/src/generator.dart:629:38)
E/flutter ( 7499): #4      _MyHomePageState.testTicket (package:discover_printers/main.dart:192:26)
E/flutter ( 7499): <asynchronous suspension>
E/flutter ( 7499): #5      _MyHomePageState.testPrint (package:discover_printers/main.dart:396:17)
E/flutter ( 7499): <asynchronous suspension>
E/flutter ( 7499):

**Comment by xSuperMu** [comment]
Version: 4.1.2

Having this error.

E/flutter (14896): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..254096: 254097
E/flutter (14896): #0      List.[] (dart:core-patch/growable_array.dart:254:60)
E/flutter (14896): #1      Generator._packBitsIntoBytes (package:esc_pos_utils/src/generator.dart:207:16)
E/flutter (14896): #2      Generator._toRasterFormat (package:esc_pos_utils/src/generator.dart:193:12)
E/flutter (14896): #3      Generator.imageRaster (package:esc_pos_utils/src/generator.dart:629:38)
E/flutter (14896): #4      NetworkPrinter.imageRaster (package:esc_pos_printer/src/network_printer.dart:130:28)
E/flutter (14896): #5      _MyHomePageState._print (package:thermal_printer_test/main.dart:190:15)
E/flutter (14896): <asynchronous suspension>

**Comment by assem16399** [comment]
Has any one found a solution?

**Comment by assem16399** [comment]
@mjafartp @xSuperMu @sbrsubuvga 
Has anyone found any solutions?

**Comment by xSuperMu** [comment]
@assem16399 That was on a very old project of mine. Sorry I can't help you with that. Thanks.

**Comment by TamirlanBir** [comment]
@assem16399 Did u solve it ?
