### ISSUE TITLE
 java.io.IOException: bt socket closed, read return: -1 ,E/BluetoothPort( 3935): connection device is lost, E/DeviceConnFactoryManager( 3935):  read 0

### ISSUE THREAD

**Issue by rekiyagami** [andrey-ushakov/esc_pos_printer#99]
```D/ColorViewRootUtil( 3935): nav bar mode ignore false downX 559 downY 2100 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=559.0, y[0]=2100.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=57229608, downTime=57229608, deviceId=4, source=0x1002, displayId=0 }
D/ColorViewRootUtil( 3935): nav bar mode ignore false downX 602 downY 613 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=602.0, y[0]=613.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=57231537, downTime=57231537, deviceId=4, source=0x1002, displayId=0 }
I/flutter ( 3935): Instance of 'PrinterBluetooth'
D/BluetoothBasicPlugin( 3935): start scan
D/BluetoothAdapter( 3935): isLeEnabled(): ON
E/CheckPermission( 3935): _bluetooth code = 10
D/BluetoothLeScanner( 3935): onScannerRegistered() - status=0 scannerId=5 mScannerId=0
D/BluetoothAdapter( 3935): isLeEnabled(): ON
D/BluetoothLeScanner( 3935): could not find callback wrapper
D/BluetoothAdapter( 3935): cancelDiscovery(): called by: com.example.mj_project
W/BluetoothAdapter( 3935): getBluetoothService() called with no BluetoothManagerCallback
D/BluetoothBasicPlugin( 3935): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
E/DeviceConnFactoryManager( 3935): wait read
D/BluetoothSocket( 3935): close() this: android.bluetooth.BluetoothSocket@b7fc64f, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@3edb1dc, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@48df2e5mSocket: android.net.LocalSocket@29061ba impl:android.net.LocalSocketImpl@51c786b fd:java.io.FileDescriptor@7920fc8, mSocketState: CONNECTED
D/BluetoothSocket( 3935): close() this: android.bluetooth.BluetoothSocket@b7fc64f, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@3edb1dc, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@48df2e5mSocket: null, mSocketState: CLOSED
W/System.err( 3935): java.io.IOException: bt socket closed, read return: -1
W/System.err( 3935): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:564)
W/System.err( 3935): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
W/System.err( 3935): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err( 3935): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err( 3935): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:418)
W/System.err( 3935): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:498)
E/BluetoothPort( 3935): connection device is lost
E/DeviceConnFactoryManager( 3935):  read 0
D/BluetoothBasicPlugin( 3935): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED```



I have this problem when I try to connect the device to my printer, but Bluetooth is instantly disconnected from the device.

Does eos not support all thermal devices?
flutter doc is no problem, bluetooth permission has been granted, the printer is in good condition  :(((

**Comment by chaiyifam** [comment]
not all device support this library....
have to write some custom script
